language: node_js
node_js:
- '0.11'
before_install:
- npm install -g bower grunt-cli
- cd src
- bower install
- bower install mapbox.js
- bower install bootstrap-theme-bootswatch-flatly
install:
- pwd
- npm install
before_script:
- pwd
- grunt build
script:
- pwd
- npm test
services: mongodb
after_success:
- sudo apt-get -y install sshpass
- sshpass -p $DEPLOY_PASS ssh -v -oStrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST touch travis_build_trigger
notifications:
  email:
    recipients:
      - ed.hollingsworth@ionep.com
      - steven.ferrell@ionep.com
      - steve.winkler@ionep.com
env:
  global:
  - secure: nahDgMTegeP+z/RI8rlZp6DVLSY5LLhVn33UVb57BsBZf2GLTu1QWuY3osCq9OO3WuBfTdfB980nYpZfNoyePP3ktcLyEJQ6yM0ZLpxxQEYCHQ1Elnt3MpJs2+GAFLp9G752nNRmpOgOPv6ub3GSXBr66gJ4Pq0I7qT5+1muZo1s+FI8i+4PZlOFO9gXoUGa0+P/jk9MzjYK+J9AoDx/IMIgUOPuzVCbQNFklpR9z6eL9wRnYGYya2Jwwjp0NMC60XW9lFL+ncT4+mEHKK3ZbhYka7jYKFh8slDq/L946X1OATaeZg+l+qT+jeBCpusqoCKbJcGMbXF2vmCjJl1nMZ1ctzyGHVAUuLeJoWgWqpkbZiapBBz/bJo52v4bb+pYKWUi1j07Ic3/uJ/EmkF0TEgK9Utzr0mUySzw8QBRkhf93JqMK9zKsZjsVFRHFuUVTqnXvTeCnmCuqZdNwZ7cfGa1FqHfS5f4QUUOq0M+gpElmjBBO6INzrdA1/+etx7L1jpDZH85J0Xwpn6OiZz7HuLDg/pNxHD0aVbzeCCr9SpOnpiZCRKXu0rxYa6jUntTMQoimMsrGR5VDJJihVJqOS9V3/hhjRP0ph5q3qZKRMxrmrBRlNpjjBgsdk6FZZzr61gtAEZCJxcm2Cfb5IdRkqG3VMe1CgS7YSO04TP4cSo=
  - secure: RpiU22csUjup2wNmep/WqtPP5k9x0hv80PgREyFEaLj8VbFSMSN00nNN4dL8LK24MSYzTqbwJOH7m1JtBf398EQbEbS06aweg71yWpfavaxGxyCb4aS8DoPrNNwS6YW638CWW3os38f41jPkj0ncZx4Ts/x8fBUDLyXY9Rh3iFlp2km97vy7SaduWsgfIRSxGNSJwnHzlwhoVRQXAFBvtm9VuQAVTClFFWPH/rc7rFSBP1ujqqTAOir6P3sCRKCTToGqQiyITCJRYeyXti9BlsuiVkbapc6fGx66uzgqGY+E/dyR6FF+12qrYRrmj9Zsa0c/AfFPF4Cvxyf67RaYup1383FIeSNNITCpbZpxVFrtAzYAoa7RmVzehDjXKUuXMuboDaJjczd7OKaeAzKP5TPqtyWck2X7MEUeAOLSMbfG2vscnSY6T5YE1h3NaT/zPry5JVcws1RueNKmHAvwlJZ29S7ucTMVQxNR88LLGuWqCIXabd+O2I1KMz7tQFNcBZf7D3HC9WYVrbRUZU11ZU1jCpxcQruiFhBJ5QGNqd12PFXlV2rpmwvPRVEC9BJsP6SGS4A7W5ZniAJDQDUj73idv/yEMWWMyyPArVgWIQ+Ap3+2gisVR9nBwvgmhXTk3svUKK9Ia9Q+XXiqDl2j6iWzr264iXv6h1UWEWZ5wLk=
  - secure: S6l0lG21iPg1unA1eoz+lXPEIe3raMKixZUuuHUYxHWuZESwY6nh8cU+vr1bTlut+2Fg5a8vuVbrRxB1bSv0ju8xc/zVTUbSPgo5tp9xpE9NGW+O8gD9aI6QAGtjSIUxe6/Bd1xCePZ9n9bT9O4HW/SkEQLsQBPpfWMMI5C2g13Pbbg5yQPXgK916I24wxbMOqdm/wvDmXzoDRvOW6ARJbfCmQiw12hJQmcr8fJ11SBl4IVTpyd42IaeUjZZ/2/DZ74gws+v1Q5ybNoSPthD2hR88Yprc8Uk+AgrWlaX8JF8uW1vvIOT1J6vY6RmteQqDl/6Q7sKMsRq7vDbrPzGgHfh8KwTXvEylTv/r2fJS67HKnnM+pIwmC5rF5KrJJHI4YTUTyVz0UeAYemvS365GJN9b4XhPqnoiqJRcAqIVxgLHPfEfZ8mUtEB2ldr/CnlJDYcS7H6O0gWlK2AAYnTVA6piIWBmKUM4sM2Hy9iLR2WlKfTS7FrOghDFI9R6yQCQYn6S6XrqHZa8EdV8hCfQmfqXHtES4nvhzQ6pg7yKB6pAU5h0qTI69Hiys13FnL0X/+tPWE9v6dE3aMIV52h9fWmvZtViQDEjxJB0eoCcKfrasrciQo+l7ROOmIz+Sp7Pp492s4I4df6dgIJyBtNEfRtHGjc4Kn1iFesg+AkKZw=
