language: node_js
node_js:
- '0.11'
before_install:
- npm install -g bower grunt-cli
- cd src
- bower install
- bower install mapbox.js
- echo "1" | bower install bootstrap-theme-bootswatch-flatly
install:
- pwd
- npm install
before_script:
- pwd
- grunt build
script:
- pwd
- npm test
services: mongodb
after_success:
- sudo apt-get -y install sshpass
- sshpass -p $DEPLOY_PASS ssh -oStrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST touch travis_build_trigger
notifications:
  email:
    recipients:
      - ed.hollingsworth@ionep.com
      - steven.ferrell@ionep.com
      - steve.winkler@ionep.com
env:
  global:
  - secure: w6fG7lfaFC3MXZcg9MFOaJmzDBmyHsLcd4JbYgwZ2aM83hVH9Efo6gbPnfxWA0So6lhpz5h4oCE+XnKbw+CQ9g54g+HRSZUorn1WjOvD/YvqEVgLHfX6666iS8y1LfMMKRIZeQeNPRd2nkmWoJ0+jIYBBjavr4vfNOevojeXvOovNvyEXBkRfw5Tnynhyoueruj++aELArZlpI4TBaQyrtOUlAoh9z6gDimtr0Git/tKDEdX7K3JYZ6CatNs0dtsQGHp0jTFYgikzd+3nDZ0+9+HZvqXiDU0d6RUfrBFk6fBF0jufqmOMKtqayQRylLyA8aBTHR/Zo5gUWaj9Zpz6zRqLXDu/8hRH4+QV+QdDb6VqkKC4MPEO8oWTPHL8uaZP/3Daf7b+Bt2BgyssYkbZJTnFIKdO6w5v4sYYkLM26UWeSWSegobXi9ImIJ3+eJoFC5lKEI/aU2t1+ZHAN2F+Jdrl1SVzzk7NdskxUtvEevLaqZ9NldywHOOIAsu0mcZZdMB7Bl47C+wr+Z2STaKB794jf8D56DP1hX3Fy1mKDGGR3xcrR7P2sfq78mgvDKBmXeJg+9qfY3DCs3UkeRAgveY4MCDZC+G7en3v5TXzkLMFIsFljBGCo1oHmHt/2a0MVHi9sqEX93BZOYhvMMgM0tpiXPFff2bI6TVTmk1O0g=
  - secure: iseNNphRpHZuFIK3doHau4uC1pHLCgxY7kExiZFvOAFP0rQK0CqMpeJbhA++6QC5AUU8cgcIQwYrI9lMnfu4DNCDho9U0U6xEp5EjEptEdRjKvVe/NG6/9YWHyPeCz0yiLMg/Nu8khMw6xaT+JN7U53rmEwxR3ibnf/8qtupcqmUA18dnH72ZElbhT4mkvrLWSGr5HsOqdwfsN1z9siz3EMm+BcovIDLTNOfZPanBMAw6XiERszJ8FQ1GjGYrR1UOuVUQxlsyex8zMJLotqZxrROPyIUsQeDbWqSKnjXotoHZSb4Mg2zkFUuQM423ZOA5L+uZT+wqYwtCrlFoAiPe93eSgKntq5cZyRjQBWCBCycSQRvpk8lBYADC2QCQpnYSWIBQhbYYTqR5Suywj8nG4OFG9llrDnKmNI7jJqoVkLIbf7ic/sFaTjQgq6Ykb7kljyK2pU7IheuwywbBnuptfx8ZoGm1o4/lg0xk718Bz27DU2BMxdrk485QULhlGQe4D5y+v/wJCSXwF+pknRA1hzJJf+h4sXclZRa0pbm8jBVXoC8bmtleockAxh7Cs/Sf45QJDjIsxe3zbo9Qe3HnHCPONHOyvQkLyZ7HmAOM9Q2H0aMNiYAQXr8Z9RJVYQsG737zfzY9vFXA1DZPtJNPUpv3iXgr2tDXBvh29QBj8c=
  - secure: u2bQWV0EgmWoBxT+L6bXvFq6Yn7proI2v+hnViaCqvM1p0oDnN5LZJhrsNQRYHJyruns4ED5BkLV0s2CCbiH18qQ6811jZAwACwcORuBjVDk3v+dM7dCsxN+xR0KNFHSI3Q4CkeUOUgcf4AtDaJip5j8ImQQcJxhHB0knvB4ZBucZBTW193+jpJw2KPptOKmEgBB/6dGQe/Ey958M3Q8c404jLbc5O6ubujSTUpUlN+062ABqrqt4+XrROnoG5mE9cSQeuxaGO54Kvp3Q0f06steGe5AoCD+9E0ers4rawD87kVlQvUUbKgSUCt1mSNnXzk8csIv1SxkTOz+KRc8ZGBAb9THneUckrlXcoPUeHg1IRohGulZvhYVDiawUrVJtWlbbYozJgDb1cDWtyQ4zooK22u+VHG5ExfRd8Hip1FY4/VQFxjaxd91PdK4MZOD6aM3P3OmSTwAHCvcTonYmYXMSToiD/oyffpeQsZSSYzsdbcAKOVH3P9dgU2hMbH4TDoWE7r1DKmd2Mqj3H9QubM5ki/zG2dXrFvSgTAZ+Bol4GnReMT4NdzxXd2VcHs434Gz610wNf6SCOth0PExmoI9M02nXRTeuychmegDCajMzpRxh+idoTQWC5/5qZ09nX8tn1skvxlA7SoPsGXOL9Gfvi3JVddGaKgT/DV6MsI=
